### ISSUE TITLE
Returning to base when full incremented shaft count

### ISSUE THREAD

**Issue by Sibz** [Sibz/SE_DrillShipNav#6]
when returning to roid after, it starts on next shaft.

**Comment by mrsib** [comment]
Checked ship log, shaft wasn't incremented, but it appeared to mine next shaft. Continuing investigations.

**Comment by mrsib** [comment]
This was observed once also when setting the starting shaft manually, and started script at toRoid(). it went on to the 'next' shaft. the shaft I manually set was the last one in debug log

**Comment by mrsib** [comment]
Move to next sprint as quite illusive and hard to reproduce. Need more information.
